#!/usr/bin/env python

import sys

tokens = sys.stdin.read().strip().split()

voc = {}

for token in tokens:
    if voc.get(token):
        voc[token] += 1
    else:
        voc[token] = 1

print '\n'.join(str((v, k)) for k, v in sorted([(v, k) for k, v in voc.items()], reverse=True))
