#!/usr/bin/env python

import sys

tokens = sys.stdin.read().strip().split()

voc = {}

for token in tokens:
    if voc.get(token):
        voc[token] += 1
    else:
        voc[token] = 1

print '\n'.join('{}\t{}'.format(k, v) for k, v in voc.items())
